#include <stdio.h>
#include <cuda.h>
#include "export.h"

// this can be generated by a pre processor
typedef void (*test_fun)(int x);
__device__ void send(int x){
	printf("Number is %d\n", x);
}
__device__ test_fun send_dev_ptr = send;

extern "C"
void* gen_host_send_ptr(){
	test_fun local;
	cudaMemcpyFromSymbol(&local, send_dev_ptr, sizeof(test_fun));
	return (void*)local;
}


__global__
void run(test_fun wei, int x){
	(*wei)(x);
}
extern "C"
void test(int x, void* fun){
	
	run<<<1,1>>>((test_fun)fun, x);
	cudaDeviceSynchronize();
}
